services:
  - type: web
    name: internlink-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        value: myinternlinkjwtsecret2024
      - key: JWT_LIFETIME
        value: 1d
      - key: ONEMAP_EMAIL
        value: lolblackapple@gmail.com
      - key: ONEMAP_EMAIL_PASSWORD
        value: !wzCzS$Pm7sLmmy
      - key: MONGO_URI
        value: mongodb+srv://yiwencheung:eM9nvJHPsMj1flko@cluster0.nbwm6.mongodb.net?retryWrites=true&w=majority&appName=Cluster0
      - key: Client_ID
        value: 2vd8rsuy33l3j9as
      - key: Secret
        value: XpfZv5eY
      - key: Scope
        value: emsi_open

  - type: web
    name: internlink-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && VITE_API_BASE_URL=https://internlink-backend.onrender.com npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        value: https://internlink-backend.onrender.com # Replace with the actual backend render URL
