services:
  - type: web
    name: mern-app
    env: node
    plan: free
    buildCommand: |
      npm install
      cd frontend && npm install
      cd ../backend && npm install
    startCommand: npm run dev
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 18
